GET /users HTTP/1.1
Host: localhost:3001
Content-Type: application/json; charset=utf-8

{
    "password": "yo123",
    "username": "eener"
}
###

POST /users/new HTTP/1.1
Host: localhost:3001
Content-Type: application/json; charset=utf-8

{
    "password": "yo",
    "username": "eener"
}


